'use client'

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Brain } from 'lucide-react'

interface Suggestion {
  id: number
  priority: 'High' | 'Medium' | 'Low'
  title: string
  reasoning: string
  impact: string
}

const suggestions: Suggestion[] = [
  {
    id: 1,
    priority: 'High',
    title: 'Reduce equity concentration in IT sector',
    reasoning: '38% of your equity allocation is in IT stocks (TCS, INFY, WIPRO). This increases sector-specific risk.',
    impact: 'Could reduce Risk Score from 42 to ~35',
  },
  {
    id: 2,
    priority: 'Medium',
    title: 'Increase Fixed Income allocation',
    reasoning: 'Your Fixed Income exposure (15%) is below the recommended 20-25% for your risk profile.',
    impact: 'Could improve Diversification Score by ~6 pts',
  },
  {
    id: 3,
    priority: 'Medium',
    title: 'Consider adding international exposure',
    reasoning: '100% of your equity holdings are India-focused. Global diversification can reduce country-specific risk.',
    impact: 'Improves long-term risk-adjusted returns',
  },
  {
    id: 4,
    priority: 'Low',
    title: 'Rebalance Gold allocation',
    reasoning: 'Gold allocation (10%) is near optimal for current market volatility. No urgent action needed.',
    impact: 'Maintains current hedge position',
  },
]

const priorityColors = {
  High: 'bg-[var(--icon-red-bg)] text-[var(--icon-red-text)]',
  Medium: 'bg-[var(--icon-amber-bg)] text-[var(--icon-amber-text)]',
  Low: 'bg-[var(--icon-blue-bg)] text-[var(--icon-blue-text)]',
}

export function AISuggestions() {
  return (
    <Card className="bg-[var(--bg-card)] border-[var(--border-color)] shadow-[var(--card-shadow)]">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Brain className="h-5 w-5 text-[var(--icon-purple-text)]" />
            <CardTitle className="text-lg text-[var(--text-primary)]">AI Portfolio Suggestions</CardTitle>
          </div>
          <Badge className="bg-[var(--icon-purple-bg)] text-[var(--icon-purple-text)]">AI Powered</Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {suggestions.map((suggestion) => (
          <div
            key={suggestion.id}
            className="border border-[var(--border-color)] rounded-lg p-4 space-y-3 hover:bg-[var(--bg-hover)] transition-colors"
          >
            <div className="flex items-start justify-between gap-3">
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-1">
                  <Badge className={priorityColors[suggestion.priority]}>
                    {suggestion.priority} Priority
                  </Badge>
                </div>
                <h4 className="font-semibold text-[var(--text-primary)]">{suggestion.title}</h4>
              </div>
            </div>

            <p className="text-sm text-[var(--text-secondary)] leading-relaxed">
              {suggestion.reasoning}
            </p>

            <div className="bg-[var(--bg-card-inner)] rounded p-2 text-xs">
              <span className="font-medium text-[var(--text-primary)]">Impact: </span>
              <span className="text-[var(--text-secondary)]">{suggestion.impact}</span>
            </div>

            <div className="flex gap-2">
              <Button size="sm" className="flex-1">
                Apply Suggestion
              </Button>
              <Button size="sm" variant="outline" className="flex-1">
                View Details
              </Button>
            </div>
          </div>
        ))}

        <p className="text-xs text-[var(--text-muted)] mt-6 pt-4 border-t border-[var(--border-color)]">
          Suggestions are generated by Chronos AI based on your portfolio composition and market conditions. Not investment advice.
        </p>
      </CardContent>
    </Card>
  )
}
